 
# GET http://localhost:3000/user-info
# Content-Type: application/json 


# POST  http://localhost:3000/signup
# Content-Type: application/json 
  
# {
#      "fullname" : "John Doe",
#      "email": "johndoe@apricodex.com",
#      "password":"123456",
# }



  
POST  http://localhost:3000/save-location
Content-Type: application/json 

{
      "uid" : "kh4kh43uh34hkrh34", 
      "timeOfFlight" : "2023-10-01T12:00:00Z",
      "hc" : "123456",
      "latitude" : "23.32342432",
      "longitude" : "23.32342432",
      "bearning" : "23.32342432",
      "direction" : "23.32342432", 
      "datetime" : "2023-10-01T12:00:00Z"
}
 